package day39_b_exeption.learn_exception;

public class FourthTry {
}
